name = "agora-worker"
main = "src/index.ts"
compatibility_date = "2026-01-01"

[vars]
R2_PUBLIC_BASE = "https://cdn.plateforme-agora.fr"
FRONTEND_URL = "https://plateforme-agora.fr"
EMAIL_FROM = "Agora <contact@plateforme-agora.fr>"
EMAIL_REPLY_TO_PROSPECTION = "prospection@replies.plateforme-agora.fr"

[[r2_buckets]]
binding = "BUCKET_R2"
bucket_name = "newappcitoyenne-uploads"

[triggers]
crons = ["0 3 1 * *", "0 4 * * *", "0 */6 * * *", "0 6 * * *"]
